services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: bossEyeServer
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo
    env_file:
      - .env.docker
    volumes:
      - ./server:/server
      - /server/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: bossEyeClient
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000
    volumes:
      - ./client:/client
      - /client/node_modules
  discord-bot:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    container_name: bossEyeDiscordBot
    restart: unless-stopped
    depends_on:
      - server
    env_file:
      - ./discord-bot/.env.docker
    volumes:
      - ./discord-bot:/bot
      - /bot/node_modules

  mongo:
    image: mongo:7
    container_name: bossEye_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - bossEye_mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: bossEye_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - bossEye_redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: bossEye_redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - bossEye_redisinsight_data:/data

volumes:
  bossEye_mongo_data:
  bossEye_redis_data:
  bossEye_redisinsight_data:
